# Generated by Django 3.0.3 on 2020-03-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_fc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fc',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=3),
        ),
    ]
