# Generated by Django 3.0.3 on 2020-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200316_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fc',
            field=models.BooleanField(),
        ),
    ]
