# Generated by Django 3.0.3 on 2020-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200316_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fc',
            field=models.BooleanField(default=False),
        ),
    ]
