# Generated by Django 3.0.3 on 2020-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200316_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fc_setup',
            field=models.BooleanField(default=False),
        ),
    ]
