# Generated by Django 3.0.3 on 2020-03-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
