# Generated by Django 3.0.3 on 2020-03-29 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic',
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='mainPic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
