# Generated by Django 3.0.3 on 2020-03-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200329_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
