# Generated by Django 3.0.3 on 2020-03-29 09:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_fc_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fc_pic',
            field=models.ImageField(null=True, upload_to=users.models.user_directory_path),
        ),
    ]
