# Generated by Django 3.0.3 on 2020-03-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200329_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fc_pic',
            field=models.ImageField(null=True, upload_to='face_images'),
        ),
        migrations.CreateModel(
            name='FcPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(null=True, upload_to='face_images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
