# Generated by Django 3.0.3 on 2020-05-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200329_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fc_pic',
        ),
    ]
