# Generated by Django 3.0.5 on 2020-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contactno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
