# Generated by Django 3.0.3 on 2020-06-03 09:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200603_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='Singapore', max_length=2),
        ),
    ]
