version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "80:80"
#    volumes:
#    - .:/django


  db:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
    - "3306:3306"
    expose:
      - '3306'




