Countries = {'Aruba': 'ABW',
             'Afghanistan': 'AFG',
             'Angola': 'AGO',
             'Anguilla': 'AIA',
             'Åland Islands': 'ALA',
             'Albania': 'ALB',
             'Andorra': 'AND',
             'United Arab Emirates': 'ARE',
             'Argentina': 'ARG',
             'Armenia': 'ARM',
             'American Samoa': 'ASM',
             'Antarctica': 'ATA',
             'French Southern Territories': 'ATF',
             'Antigua and Barbuda': 'ATG',
             'Australia': 'AUS',
             'Austria': 'AUT',
             'Azerbaijan': 'AZE',
             'Burundi': 'BDI',
             'Belgium': 'BEL',
             'Benin': 'BEN',
             'Bonaire, Sint Eustatius and Saba': 'BES',
             'Burkina Faso': 'BFA',
             'Bangladesh': 'BGD',
             'Bulgaria': 'BGR',
             'Bahrain': 'BHR',
             'Bahamas': 'BHS',
             'Bosnia and Herzegovina': 'BIH',
             'Saint Barthélemy': 'BLM',
             'Belarus': 'BLR',
             'Belize': 'BLZ',
             'Bermuda': 'BMU',
             'Bolivia, Plurinational State of': 'BOL',
             'Brazil': 'BRA',
             'Barbados': 'BRB',
             'Brunei Darussalam': 'BRN',
             'Bhutan': 'BTN',
             'Bouvet Island': 'BVT',
             'Botswana': 'BWA',
             'Central African Republic': 'CAF',
             'Canada': 'CAN',
             'Cocos (Keeling) Islands': 'CCK',
             'Switzerland': 'CHE',
             'Chile': 'CHL',
             'China': 'CHN',
             'Côte d\'Ivoire': 'CIV',
             'Cameroon': 'CMR',
             'Congo, The Democratic Republic of the': 'COD',
             'Congo': 'COG',
             'Cook Islands': 'COK',
             'Colombia': 'COL',
             'Comoros': 'COM',
             'Cabo Verde': 'CPV',
             'Costa Rica': 'CRI',
             'Cuba': 'CUB',
             'Curaçao': 'CUW',
             'Christmas Island': 'CXR',
             'Cayman Islands': 'CYM',
             'Cyprus': 'CYP',
             'Czechia': 'CZE',
             'Germany': 'DEU',
             'Djibouti': 'DJI',
             'Dominica': 'DMA',
             'Denmark': 'DNK',
             'Dominican Republic': 'DOM',
             'Algeria': 'DZA',
             'Ecuador': 'ECU',
             'Egypt': 'EGY',
             'Eritrea': 'ERI',
             'Western Sahara': 'ESH',
             'Spain': 'ESP',
             'Estonia': 'EST',
             'Ethiopia': 'ETH',
             'Finland': 'FIN',
             'Fiji': 'FJI',
             'Falkland Islands (Malvinas)': 'FLK',
             'France': 'FRA',
             'Faroe Islands': 'FRO',
             'Micronesia, Federated States of': 'FSM',
             'Gabon': 'GAB',
             'United Kingdom': 'GBR',
             'Georgia': 'GEO',
             'Guernsey': 'GGY',
             'Ghana': 'GHA',
             'Gibraltar': 'GIB',
             'Guinea': 'GIN',
             'Guadeloupe': 'GLP',
             'Gambia': 'GMB',
             'Guinea-Bissau': 'GNB',
             'Equatorial Guinea': 'GNQ',
             'Greece': 'GRC',
             'Grenada': 'GRD',
             'Greenland': 'GRL',
             'Guatemala': 'GTM',
             'French Guiana': 'GUF',
             'Guam': 'GUM',
             'Guyana': 'GUY',
             'Hong Kong': 'HKG',
             'Heard Island and McDonald Islands': 'HMD',
             'Honduras': 'HND',
             'Croatia': 'HRV',
             'Haiti': 'HTI',
             'Hungary': 'HUN',
             'Indonesia': 'IDN',
             'Isle of Man': 'IMN',
             'India': 'IND',
             'British Indian Ocean Territory': 'IOT',
             'Ireland': 'IRL',
             'Iran, Islamic Republic of': 'IRN',
             'Iraq': 'IRQ',
             'Iceland': 'ISL',
             'Israel': 'ISR',
             'Italy': 'ITA',
             'Jamaica': 'JAM',
             'Jersey': 'JEY',
             'Jordan': 'JOR',
             'Japan': 'JPN',
             'Kazakhstan': 'KAZ',
             'Kenya': 'KEN',
             'Kyrgyzstan': 'KGZ',
             'Cambodia': 'KHM',
             'Kiribati': 'KIR',
             'Saint Kitts and Nevis': 'KNA',
             'Korea, Republic of': 'KOR',
             'Kuwait': 'KWT',
             'Lao People\'s Democratic Republic': 'LAO',
             'Lebanon': 'LBN',
             'Liberia': 'LBR',
             'Libya': 'LBY',
             'Saint Lucia': 'LCA',
             'Liechtenstein': 'LIE',
             'Sri Lanka': 'LKA',
             'Lesotho': 'LSO',
             'Lithuania': 'LTU',
             'Luxembourg': 'LUX',
             'Latvia': 'LVA',
             'Macao': 'MAC',
             'Saint Martin (French part)': 'MAF',
             'Morocco': 'MAR',
             'Monaco': 'MCO',
             'Moldova, Republic of': 'MDA',
             'Madagascar': 'MDG',
             'Maldives': 'MDV',
             'Mexico': 'MEX',
             'Marshall Islands': 'MHL',
             'North Macedonia': 'MKD',
             'Mali': 'MLI',
             'Malta': 'MLT',
             'Myanmar': 'MMR',
             'Montenegro': 'MNE',
             'Mongolia': 'MNG',
             'Northern Mariana Islands': 'MNP',
             'Mozambique': 'MOZ',
             'Mauritania': 'MRT',
             'Montserrat': 'MSR',
             'Martinique': 'MTQ',
             'Mauritius': 'MUS',
             'Malawi': 'MWI',
             'Malaysia': 'MYS',
             'Mayotte': 'MYT',
             'Namibia': 'NAM',
             'New Caledonia': 'NCL',
             'Niger': 'NER',
             'Norfolk Island': 'NFK',
             'Nigeria': 'NGA',
             'Nicaragua': 'NIC',
             'Niue': 'NIU',
             'Netherlands': 'NLD',
             'Norway': 'NOR',
             'Nepal': 'NPL',
             'Nauru': 'NRU',
             'New Zealand': 'NZL',
             'Oman': 'OMN',
             'Pakistan': 'PAK',
             'Panama': 'PAN',
             'Pitcairn': 'PCN',
             'Peru': 'PER',
             'Philippines': 'PHL',
             'Palau': 'PLW',
             'Papua New Guinea': 'PNG',
             'Poland': 'POL',
             'Puerto Rico': 'PRI',
             'Korea, Democratic People\'s Republic of': 'PRK',
             'Portugal': 'PRT',
             'Paraguay': 'PRY',
             'Palestine, State of': 'PSE',
             'French Polynesia': 'PYF',
             'Qatar': 'QAT',
             'Réunion': 'REU',
             'Romania': 'ROU',
             'Russian Federation': 'RUS',
             'Rwanda': 'RWA',
             'Saudi Arabia': 'SAU',
             'Sudan': 'SDN',
             'Senegal': 'SEN',
             'Singapore': 'SGP',
             'South Georgia and the South Sandwich Islands': 'SGS',
             'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
             'Svalbard and Jan Mayen': 'SJM',
             'Solomon Islands': 'SLB',
             'Sierra Leone': 'SLE',
             'El Salvador': 'SLV',
             'San Marino': 'SMR',
             'Somalia': 'SOM',
             'Saint Pierre and Miquelon': 'SPM',
             'Serbia': 'SRB',
             'South Sudan': 'SSD',
             'Sao Tome and Principe': 'STP',
             'Suriname': 'SUR',
             'Slovakia': 'SVK',
             'Slovenia': 'SVN',
             'Sweden': 'SWE',
             'Eswatini': 'SWZ',
             'Sint Maarten (Dutch part)': 'SXM',
             'Seychelles': 'SYC',
             'Syrian Arab Republic': 'SYR',
             'Turks and Caicos Islands': 'TCA',
             'Chad': 'TCD',
             'Togo': 'TGO',
             'Thailand': 'THA',
             'Tajikistan': 'TJK',
             'Tokelau': 'TKL',
             'Turkmenistan': 'TKM',
             'Timor-Leste': 'TLS',
             'Tonga': 'TON',
             'Trinidad and Tobago': 'TTO',
             'Tunisia': 'TUN',
             'Turkey': 'TUR',
             'Tuvalu': 'TUV',
             'Taiwan, Province of China': 'TWN',
             'Tanzania, United Republic of': 'TZA',
             'Uganda': 'UGA',
             'Ukraine': 'UKR',
             'United States Minor Outlying Islands': 'UMI',
             'Uruguay': 'URY',
             'United States': 'USA',
             'Uzbekistan': 'UZB',
             'Holy See (Vatican City State)': 'VAT',
             'Saint Vincent and the Grenadines': 'VCT',
             'Venezuela, Bolivarian Republic of': 'VEN',
             'Virgin Islands, British': 'VGB',
             'Virgin Islands, U.S.': 'VIR',
             'Vietnam': 'VNM',
             'Vanuatu': 'VUT',
             'Wallis and Futuna': 'WLF',
             'Samoa': 'WSM',
             'Yemen': 'YEM',
             'South Africa': 'ZAF',
             'Zambia': 'ZMB',
             'Zimbabwe': 'ZWE'}

Country_to_continents = {
                'Aruba': 'North America',
                'Afghanistan': 'Asia',
                'Angola': 'Africa',
                'Anguilla': 'North America',
                'Åland Islands': 'Europe',
                'Albania': 'Europe',
                'Andorra': 'Europe',
                'United Arab Emirates': 'Asia',
                'Argentina': 'South America',
                'Armenia': 'Asia',
                'American Samoa': 'Australia',
                'Antarctica': 'Antarctica',
                'French Southern Territories': 'Antarctica',
                'Antigua and Barbuda': 'North America',
                'Australia': 'Australia',
                'Austria': 'Europe',
                'Azerbaijan': 'Asia',
                'Burundi': 'Africa',
                'Belgium': 'Europe',
                'Benin': 'Africa',
                'Bonaire, Sint Eustatius and Saba': 'North America',
                'Burkina Faso': 'Africa',
                'Bangladesh': 'Asia',
                'Bulgaria': 'Europe',
                'Bahrain': 'Asia',
                'Bahamas': 'North America',
                'Bosnia and Herzegovina': 'Europe',
                'Saint Barthélemy': 'North America',
                'Belarus': 'Europe',
                'Belize': 'North America',
                'Bermuda': 'North America',
                'Bolivia, Plurinational State of': 'South America',
                'Brazil': 'South America',
                'Barbados': 'North America',
                'Brunei Darussalam': 'Asia',
                'Bhutan': 'Asia',
                'Bouvet Island': 'Antarctica',
                'Botswana': 'Africa',
                'Central African Republic': 'Africa',
                'Canada': 'North America',
                'Cocos (Keeling) Islands': 'Asia',
                'Switzerland': 'Europe',
                'Chile': 'South America',
                'China': 'Asia',
                'Côte d\'Ivoire': 'Africa',
                'Cameroon': 'Africa',
                'Congo, The Democratic Republic of the': 'Africa',
                'Congo': 'Africa',
                'Cook Islands': 'Australia',
                'Colombia': 'South America',
                'Comoros': 'Africa',
                'Cabo Verde': 'Africa',
                'Costa Rica': 'North America',
                'Cuba': 'North America',
                'Curaçao': 'North America',
                'Christmas Island': 'Asia',
                'Cayman Islands': 'North America',
                'Cyprus': 'Asia',
                'Czechia': 'Europe',
                'Germany': 'Europe',
                'Djibouti': 'Africa',
                'Dominica': 'North America',
                'Denmark': 'Europe',
                'Dominican Republic': 'North America',
                'Algeria': 'Africa',
                'Ecuador': 'South America',
                'Egypt': 'Africa',
                'Eritrea': 'Africa',
                'Western Sahara': 'Africa',
                'Spain': 'Europe',
                'Estonia': 'Europe',
                'Ethiopia': 'Africa',
                'Finland': 'Europe',
                'Fiji': 'Australia',
                'Falkland Islands (Malvinas)': 'South America',
                'France': 'Europe',
                'Faroe Islands': 'Europe',
                'Micronesia, Federated States of': 'Australia',
                'Gabon': 'Africa',
                'United Kingdom': 'Europe',
                'Georgia': 'Asia',
                'Guernsey': 'Europe',
                'Ghana': 'Africa',
                'Gibraltar': 'Europe',
                'Guinea': 'Africa',
                'Guadeloupe': 'North America',
                'Gambia': 'Africa',
                'Guinea-Bissau': 'Africa',
                'Equatorial Guinea': 'Africa',
                'Greece': 'Europe',
                'Grenada': 'North America',
                'Greenland': 'North America',
                'Guatemala': 'North America',
                'French Guiana': 'South America',
                'Guam': 'Australia',
                'Guyana': 'South America',
                'Hong Kong': 'Asia',
                'Heard Island and McDonald Islands': 'Antarctica',
                'Honduras': 'North America',
                'Croatia': 'Europe',
                'Haiti': 'North America',
                'Hungary': 'Europe',
                'Indonesia': 'Asia',
                'Isle of Man': 'Europe',
                'India': 'Asia',
                'British Indian Ocean Territory': 'Asia',
                'Ireland': 'Europe',
                'Iran, Islamic Republic of': 'Asia',
                'Iraq': 'Asia',
                'Iceland': 'Europe',
                'Israel': 'Asia',
                'Italy': 'Europe',
                'Jamaica': 'North America',
                'Jersey': 'Europe',
                'Jordan': 'Asia',
                'Japan': 'Asia',
                'Kazakhstan': 'Asia',
                'Kenya': 'Africa',
                'Kyrgyzstan': 'Asia',
                'Cambodia': 'Asia',
                'Kiribati': 'Australia',
                'Saint Kitts and Nevis': 'North America',
                'Korea, Republic of': 'Asia',
                'Kuwait': 'Asia',
                'Lao People\'s Democratic Republic': 'Asia',
                'Lebanon': 'Asia',
                'Liberia': 'Africa',
                'Libya': 'Africa',
                'Saint Lucia': 'North America',
                'Liechtenstein': 'Europe',
                'Sri Lanka': 'Asia',
                'Lesotho': 'Africa',
                'Lithuania': 'Europe',
                'Luxembourg': 'Europe',
                'Latvia': 'Europe',
                'Macao': 'Asia',
                'Saint Martin (French part)': 'North America',
                'Morocco': 'Africa',
                'Monaco': 'Europe',
                'Moldova, Republic of': 'Europe',
                'Madagascar': 'Africa',
                'Maldives': 'Asia',
                'Mexico': 'North America',
                'Marshall Islands': 'Australia',
                'North Macedonia': 'Europe',
                'Mali': 'Africa',
                'Malta': 'Europe',
                'Myanmar': 'Asia',
                'Montenegro': 'Europe',
                'Mongolia': 'Asia',
                'Northern Mariana Islands': 'Australia',
                'Mozambique': 'Africa',
                'Mauritania': 'Africa',
                'Montserrat': 'North America',
                'Martinique': 'North America',
                'Mauritius': 'Africa',
                'Malawi': 'Africa',
                'Malaysia': 'Asia',
                'Mayotte': 'Africa',
                'Namibia': 'Africa',
                'New Caledonia': 'Australia',
                'Niger': 'Africa',
                'Norfolk Island': 'Australia',
                'Nigeria': 'Africa',
                'Nicaragua': 'North America',
                'Niue': 'Australia',
                'Netherlands': 'Europe',
                'Norway': 'Europe',
                'Nepal': 'Asia',
                'Nauru': 'Australia',
                'New Zealand': 'Australia',
                'Oman': 'Asia',
                'Pakistan': 'Asia',
                'Panama': 'North America',
                'Pitcairn': 'Australia',
                'Peru': 'South America',
                'Philippines': 'Asia',
                'Palau': 'Australia',
                'Papua New Guinea': 'Australia',
                'Poland': 'Europe',
                'Puerto Rico': 'North America',
                'Korea, Democratic People\'s Republic of': 'Asia',
                'Portugal': 'Europe',
                'Paraguay': 'South America',
                'Palestine, State of': 'Asia',
                'French Polynesia': 'Australia',
                'Qatar': 'Asia',
                'Réunion': 'Africa',
                'Romania': 'Europe',
                'Russian Federation': 'Europe',
                'Rwanda': 'Africa',
                'Saudi Arabia': 'Asia',
                'Sudan': 'Africa',
                'Senegal': 'Africa',
                'Singapore': 'Asia',
                'South Georgia and the South Sandwich Islands': 'South America',
                'Saint Helena, Ascension and Tristan da Cunha': 'Africa',
                'Svalbard and Jan Mayen': 'Europe',
                'Solomon Islands': 'Australia',
                'Sierra Leone': 'Africa',
                'El Salvador': 'North America',
                'San Marino': 'Europe',
                'Somalia': 'Africa',
                'Saint Pierre and Miquelon': 'North America',
                'Serbia': 'Europe',
                'South Sudan': 'Africa',
                'Sao Tome and Principe': 'Africa',
                'Suriname': 'South America',
                'Slovakia': 'Europe',
                'Slovenia': 'Europe',
                'Sweden': 'Europe',
                'Eswatini': 'Africa',
                'Sint Maarten (Dutch part)': 'North America',
                'Seychelles': 'Africa',
                'Syrian Arab Republic': 'Asia',
                'Turks and Caicos Islands': 'North America',
                'Chad': 'Africa',
                'Togo': 'Africa',
                'Thailand': 'Asia',
                'Tajikistan': 'Asia',
                'Tokelau': 'Australia',
                'Turkmenistan': 'Asia',
                'Timor-Leste': 'Asia',
                'Tonga': 'Australia',
                'Trinidad and Tobago': 'North America',
                'Tunisia': 'Africa',
                'Turkey': 'Asia',
                'Tuvalu': 'Australia',
                'Taiwan, Province of China': 'Asia',
                'Tanzania, United Republic of': 'Africa',
                'Uganda': 'Africa',
                'Ukraine': 'Europe',
                'United States Minor Outlying Islands': 'North America',
                'Uruguay': 'South America',
                'United States': 'North America',
                'Uzbekistan': 'Asia',
                'Holy See (Vatican City State)': 'Europe',
                'Saint Vincent and the Grenadines': 'North America',
                'Venezuela, Bolivarian Republic of': 'South America',
                'Virgin Islands, British': 'North America',
                'Virgin Islands, U.S.': 'North America',
                'Vietnam': 'Asia',
                'Vanuatu': 'Australia',
                'Wallis and Futuna': 'Australia',
                'Samoa': 'Australia',
                'Yemen': 'Asia',
                'South Africa': 'Africa',
                'Zambia': 'Africa',
                'Zimbabwe': 'Africa'
}
