name: Docker Image CI

on:
  push:
    tags:
    - '*'
##tagging formate v1.0/v2.0 etc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to Registry
      run: |
          docker build dneo/djangocon:${GITHUB_REF:10} .
    - name: Push To Registry
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push dneo/djangocon:${GITHUB_REF:10}
          docker logout
