name: Docker ARM v7

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ARM32
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dneo/djangocon
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "arm32github"
