name: Docker Image CI

on:
  push:
    tags:
    - '*'
##tagging formate v1.0/v2.0 etc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # fetch and checkout the current commit
    - name: Checkout
      uses: actions/checkout@v2

      # get commit tag
    - name: Get the version
      id: get_version
      run: |
          echo '::tag::'
          echo ${GITHUB_REF:10}

    - name: Dockerize
      run: |
          docker build . -t dneo/djangocon:${GITHUB_REF:10}
    - name: Push To Registry
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push dneo/djangocon:${GITHUB_REF:10}
          docker logout
